
# ========= Border =========
file_panel_border = '#FEFCE5'
sidebar_border = '#FEFCE5'
footer_border = '#FEFCE5'

# ========= Border Active =========
file_panel_border_active = '#a1a5b5'
sidebar_border_active = '#a1a5b5'
footer_border_active = '#a1a5b5'
modal_border_active = '#a1a5b5'

# ========= Background (bg) =========
full_screen_bg = '#1A1815'
file_panel_bg = '#1A1815'
sidebar_bg = '#1A1815'
footer_bg = '#1A1815'
modal_bg = '#1A1815'

# ========= Foreground (fg) =========
full_screen_fg = '#ffffff'
file_panel_fg = '#ffffff'
sidebar_fg = '#ffffff'
footer_fg = '#ffffff'
modal_fg = '#ffffff'

# ========= Special Color =========
cursor = '#ffffff'
correct = '#989f9b'
error = '#E1D5B1'
hint = '#b5bbbf'
cancel = '#E1D5B1'
gradient_color = ['#1A1815', "#908b84"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#1A1815'
file_panel_top_path = '#908b84'
file_panel_item_selected_fg = '#908b84'
file_panel_item_selected_bg = '#1A1815'

# ========= Sidebar Special Items =========
sidebar_title = '#ffffff'
sidebar_item_selected_fg = '#908b84'
sidebar_item_selected_bg = '#1A1815'
sidebar_divider = '#FEFCE5'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#E1D5B1'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#989f9b'
